# Generated by Django 5.2.15 on 2026-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
    ]
